### ISSUE TITLE
Android verification fails

### ISSUE THREAD

**Issue by vivianjeng** [oskarth/mopro#45]
## Problem
In the android example app, the `verifyProof2` fails to verify a proof

https://github.com/oskarth/mopro/blob/5e2db8b6230eab8358409b186703166604d39a8c/mopro-android/Example/app/src/main/java/com/example/mopro/MainActivity.kt#L305

## Acceptance criteria
Should generate a valid proof and verify it.

**Comment by oskarth** [comment]
For which example? It could also be related to arkzkey

If we get the kotlin tests working we can compare with swift test and rule out if it is a platform-specific issue or not

**Comment by vivianjeng** [comment]
the current keccak256 circuit
it works in swift but it doesn't work in android
