### ISSUE TITLE
Trying to run the iOS example project

### ISSUE THREAD

**Issue by shreyaspapi** [oskarth/mopro#49]
- I have followed few instructions given in the docs for mopro dir, and have wasmer installed with snarkjs on global.
- While trying to run the app using simulator iPhone 15 pro, it stops unexpectedly without error and just shows cancelled.

**Comment by vivianjeng** [comment]
did you run the [prepare.sh](https://github.com/oskarth/mopro/blob/main/scripts/prepare.sh) or [prepare_ci.sh](https://github.com/oskarth/mopro/blob/main/scripts/prepare_ci.sh) script?
and also [build_ios.sh](https://github.com/oskarth/mopro/blob/main/scripts/build_ios.sh)?

**Comment by shreyaspapi** [comment]
> did you run the [prepare.sh](https://github.com/oskarth/mopro/blob/main/scripts/prepare.sh) or [prepare_ci.sh](https://github.com/oskarth/mopro/blob/main/scripts/prepare_ci.sh) script? and also [build_ios.sh](https://github.com/oskarth/mopro/blob/main/scripts/build_ios.sh)?

I ran the `prepare.sh` and `build_ios.sh` script.

**Comment by shreyaspapi** [comment]
No error while running the prepare script, but still says -

`Script did not finish successfully!`

<img width="567" alt="Screenshot 2023-12-09 at 11 47 04 AM" src="https://github.com/oskarth/mopro/assets/22324802/dfccb9a1-d3bb-4ef4-af5e-b77bfd210387">

**Comment by shreyaspapi** [comment]
> No error while running the prepare script, but still says -
> 
> `Script did not finish successfully!`
> 
> <img alt="Screenshot 2023-12-09 at 11 47 04 AM" width="567" src="https://private-user-images.githubusercontent.com/22324802/289240136-dfccb9a1-d3bb-4ef4-af5e-b77bfd210387.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMDI5NjEsIm5iZiI6MTcwMjEwMjY2MSwicGF0aCI6Ii8yMjMyNDgwMi8yODkyNDAxMzYtZGZjY2I5YTEtZDNiYi00ZWY0LWFmNWUtYjc3YmZkMjEwMzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA2MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OTE4MGQ2NjhmNzQ1OTExM2E4MWQ1MGI4YjAwODVhYjZkODU2M2E4Y2U2OGJkMTVjMDNkZWUxYzQyYzE0NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vioeb2WuyJBz9FXpzgUPNloWPFxt_E4u7L4SG5zxTvg">

Here I saw the circom installation successful - 
`
    Updating git repository `https://github.com/arkworks-rs/circom-compat.git`
`

**Comment by vivianjeng** [comment]
Oh then you should install circom here

https://docs.circom.io/getting-started/installation/

**Comment by oskarth** [comment]
@shreyaspapi did that work?

Thanks for https://github.com/oskarth/mopro/commit/4c8cfe5eb305aa6aecffb74a60ea83c40c8f02f2 @vivianjeng

**Comment by shreyaspapi** [comment]
Hey @oskarth it did work, unfortunately I didn't have time to work on top of it at the hackathon so had to pivot.

**Comment by oskarth** [comment]
Ok, please let us know if you ran into any other issues! Easiest would be TG chat. Closing this issue as main issue was resolved.
