### ISSUE TITLE
Test Scaffolding: Add latest anon-aadhaar circuit for benchmarking

### ISSUE THREAD

**Issue by oskarth** [oskarth/mopro#59]
## Problem

Context: https://github.com/oskarth/mopro/issues/57

We want a realistic circuit to try on. Current RSA Verify / Anon-Aadhaar is only 160k constraint one.

## Acceptance criteria

Either ~1m or ~1.7m constraint version should be added to repo.

## Note

Should work with cable, but when detaching might have to fix dylib integration.

**Comment by oskarth** [comment]
@Meyanis95 do you want to do this?

**Comment by Meyanis95** [comment]
Sure, you can assign it to me.

**Comment by Meyanis95** [comment]
Closing this one, since #66
