### ISSUE TITLE
Better understand crash and out of memory behavior for big circuits with many constraints

### ISSUE THREAD

**Issue by oskarth** [oskarth/mopro#60]
## Problem

Context: #57 

When running big circuits, some users have observed that mopro crashes. It is likely this is due to running out of memory, but this isn't 100% confirmed.

## Suggest approach

Run increasingly complex circuits and observe memory usage.

Can be done in parallel for desktop, Android and iOS.

## Acceptance criteria

- [x] Have clarity on why it crashes
- [x] If it is due to OOM, understand relationship between constraints and memory usage
- [x] Test up to ~1m constraints on desktop with mopro CLI tests
- [x] Test up to ~1m constraints on Android (recent device)
- [x] Test up to ~1m constraints on iOS (recent device)

Once above is done:
- [ ] Compare with other naive approaches to rule out memory leak (e.g. compare with rapidsnark or other code/literature)
- [ ] See if there's any low-hanging fruit in terms of fixes

## Notes

The more details we have about different devices and observed behavior the easier it is to debug this. Also system logs are useful to observe behavior.

**Comment by oskarth** [comment]
@Meyanis95 can you provide notes with what you've observed so far including on desktop, your iPhone model, circuit you ran and how to reproduce?

@vivianjeng can you try this on Android and see what you find?

I have yet to reproduce this on my recent iPhone but I'll try once we have easy way to run more complex circuits (see #58 and #59)

**Comment by oskarth** [comment]
Also note that this may be due to WASM witness generation (need to verify this), so once native witness generation #32 is done we should check again.

Another way to check is with #58.

**Comment by vivianjeng** [comment]
> @vivianjeng can you try this on Android and see what you find?

yes I can do this

**Comment by Meyanis95** [comment]
Sure: 

My hardware: iPhone XR (3 GB RAM)
The crash is happening 4 times on 5;
Here is a historical of what's happening on the memory usage on my phone for a successfully proof generated with a circuit with around 1 m constraints. 

![image](https://github.com/oskarth/mopro/assets/67648863/a29ccb35-a938-4535-816e-2a2f93b2dd7f)

**Comment by oskarth** [comment]
From chat:

Based on what I've seen so far we have

248mb for Keccak256 (150k constraints).
290mb for RSA verification (~160k constraints?)
1170mb for Anon-Aadhaar 900k constraints (screenshot provided above)

This would suggest, very roughly:

Hypothesis 1:
- 100mb baseline for app
- constraint usage scales linearly with memory, at around 100k constraints ~100mb constraints

Given that your device has 3GB RAM and at 1700k constraints that should be <2GB memory consumption with above model

Hypothesis 2: Crashes are due to witness generation WASM page size or related

What doesn't make sense to me is why crashes are intermittent at 4/5, and why it wouldn't show up in system logs (?)

Would like to reproduce this

---

@Meyanis95 did you check system log for any errors?

**Comment by oskarth** [comment]
Real device for AA circuits
![telegram-cloud-photo-size-1-5039992574391200969-y](https://github.com/oskarth/mopro/assets/1552237/6e107dfa-b9a9-4afd-b3a1-c40968e04222)

```
Init: 77s
Witness gen: 9s
Proofgen: 18s
```

- Memory usage (in simulator): 2.2GB
- Loading arkzkey into memory takes ~1.1GB memory, and then it climbs up to 2.2GB for proving
- In above estimation didn't take arkzkey into account, but presumably size of this also scales linearly with number of constraints
- So 2.1/1.7 ~120-130mb per 100k constraints I think (for arkzkey+constraints)
- My guess would be iPhone XR (2018) 3GB RAM is too low, because 2.2GB for this + other apps + buffer means it is forced to deallocate memory
- it'd be interesting if people with 4GB can run, both on iPhone and Android
- Run on iPhone 14 Max Pro has 6GB memory (2022)

**Comment by oskarth** [comment]
Only thing that is missing is Android numbers from @vivianjeng, then we can close this
