### ISSUE TITLE
Mopro CLI MVP

### ISSUE THREAD

**Issue by oskarth** [oskarth/mopro#78]
# Problem

A user currently has to ad hoc copy mopro or work from inside it. Users wants to work from their own repo with minimal extra fluff.

### Basic example

The most minimal way would be something like:

`mopro init --adapter circom --platform desktop hello-world` (desktop might be cli or basic, just a basic Rust app)

This will create a directory `hello-world`:

```
hello-world
|-- circuits
    | -- hello-world.circom
|-- src
 | -- core.rs
|-- README.md
|-- Cargo.toml
|-- test
    | -- hello-world.rs
```

From this directory you can run `cargo test` (for now, later on wrapped with `mopro`) and it will create a proof and verify it from Rust.

Questions:
- Simplify/default options for `init`?
- Allow circuit to be named?
- How to deal with prepare scripts (separate issue), add to folder or deal with this only through mopro (gen arkzkey etc)?

### More complex example

To be added once MVP above works. For Anon-Aadhaar (AAMO) this would be something like:

`mopro init --adapter circom --platform desktop,react-native --circuit anon-aadaar.circom project-aamo`

```
project-aamo
|-- circuits
    | -- anon-aadhaar.circom
|-- src
 | -- core.rs
 | -- platforms
     |-- ios
     |-- android
     |-- react-native
|-- README.md
|-- Cargo.toml
|-- test
    | -- project-aamo.rs
```

- This is a very rough sketch, need to make sure this makes sense and exactly what we minimally need
- This would then be placed inside a RN app
- Needs to be better understood

## Acceptance criteria

User can use `mopro init` to create a project outside of mopro monorepo.

Follow up issues for platforms etc can be added.

**Comment by Meyanis95** [comment]
It's a good base, and the file structure is clear. 

From a user POV: 
- I would like to specify the destination of the built artifacts (ios/android)
- In this setup how would I specify the bindings (device/sim/debug/release)? from the command or do you keep the config toml file?
- Does the ios folder here contain the whole Xcode project?

**Comment by oskarth** [comment]
With https://asciinema.org/a/644339 MVP is closed, for init/build/test.

Keeping issue open until I created follow up issues to capture next steps.

**Comment by oskarth** [comment]
>    I would like to specify the destination of the built artifacts (ios/android)

Done with export command

>    In this setup how would I specify the bindings (device/sim/debug/release)? from the command or do you keep the config toml file?

Config file, though we might potentially (?) want to add some kind of over-ride, not sure

>    Does the ios folder here contain the whole Xcode project?

Yes

**Comment by oskarth** [comment]
Closing this as MVP is done!
